return {
  -- {
  --   "LintaoAmons/easy-commands.nvim",
  --   -- branch = "dev",
  --   -- dir = "/Volumes/t7ex/Documents/oatnil/release/easy-commands.nvim",
  --   event = "VeryLazy",
  --   config = function()
  --     require("easy-commands").setup({
  --       disabledCommands = { "Git", "CodeAction" }, -- You can disable the commands you don't want
  --       -- It always welcome to send me back your good commands and usecases
  --       ---@type EasyCommand.Command[]
  --       myCommands = {
  --         {
  --           name = "ShowWorkspaceDiagnostics",
  --           callback = "Lspsaga show_workspace_diagnostics",
  --         },
  --         {
  --           name = "DeleteEmptyLines",
  --           callback = "g/^$/d",
  --           description = "Delete empty lines in the current file",
  --         },
  --         {
  --           name = "DistinctLines",
  --           callback = "sort u",
  --         },
  --         {
  --           name = "JoinLines",
  --           callback = "'<,'>s/\v\n/,/",
  --         },
  --         {
  --           name = "TempKeymap",
  --           callback = function()
  --             vim.ui.input({ prompt = "write your temp keymap, like: . @q" }, function(msg)
  --               vim.print("map <buffer> " .. msg)
  --               vim.api.nvim_command("map <buffer> " .. msg)
  --             end)
  --           end,
  --           description = "Create a buffer local keymap for tmp use",
  --         },
  --         {
  --           name = "GitAmend",
  --           callback = "G commit --amend",
  --           dependencies = { "tpope/vim-fugitive" },
  --         },
  --         {
  --           name = "ToggleOutline",
  --           callback = "AerialToggle",
  --           dependencies = { "https://github.com/stevearc/aerial.nvim" },
  --         },
  --         {
  --           name = "AddSnippet",
  --           callback = function()
  --             require("scissors").addNewSnippet()
  --           end,
  --           dependencies = { "https://github.com/chrisgrieser/nvim-scissors" },
  --         },
  --         {
  --           name = "EditSnippet",
  --           callback = function()
  --             require("scissors").editSnippet()
  --           end,
  --           dependencies = { "https://github.com/chrisgrieser/nvim-scissors" },
  --         },
  --       },
  --       aliases = {
  --         {
  --           from = "GitListCommitsOfCurrentFile",
  --           to = "FileHistory",
  --         },
  --         {
  --           from = "Dired",
  --           to = "SwitchDirectory",
  --         },
  --         {
  --           from = "DebugStart",
  --           to = "DebugContinue",
  --         },
  --       },
  --     })
  --   end,
  -- },
}
